FROM alpine:3.20.0
RUN apk add --no-cache \
        cmake \
        git

ARG LLVM_DIR=/opt/llvm
ARG LLVM_VERSION="18.1.6"
RUN git clone https://github.com/llvm/llvm-project.git /tmp/llvm \
 && cd /tmp/llvm \
 && git checkout "llvmorg-${LLVM_VERSION}"

RUN apk add --no-cache \
        musl-dev \
        ninja
